/*
 * rusty-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AcceptInviteReturnType {
    #[serde(rename = "ciphertext")]
    pub ciphertext: String,
    #[serde(rename = "invite_id")]
    pub invite_id: String,
    #[serde(rename = "project_id")]
    pub project_id: String,
}

impl AcceptInviteReturnType {
    pub fn new(ciphertext: String, invite_id: String, project_id: String) -> AcceptInviteReturnType {
        AcceptInviteReturnType {
            ciphertext,
            invite_id,
            project_id,
        }
    }
}

