/*
 * rusty-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AcceptInviteBody {
    #[serde(rename = "verifier")]
    pub verifier: String,
}

impl AcceptInviteBody {
    pub fn new(verifier: String) -> AcceptInviteBody {
        AcceptInviteBody {
            verifier,
        }
    }
}

