/*
 * rusty-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddUserBody {
    #[serde(rename = "user_id")]
    pub user_id: String,
}

impl AddUserBody {
    pub fn new(user_id: String) -> AddUserBody {
        AddUserBody {
            user_id,
        }
    }
}

