/*
 * rusty-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InviteBody {
    #[serde(rename = "ciphertext")]
    pub ciphertext: String,
    #[serde(rename = "exp")]
    pub exp: String,
    #[serde(rename = "project_id")]
    pub project_id: uuid::Uuid,
}

impl InviteBody {
    pub fn new(ciphertext: String, exp: String, project_id: uuid::Uuid) -> InviteBody {
        InviteBody {
            ciphertext,
            exp,
            project_id,
        }
    }
}

