/*
 * rusty-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InviteResponse {
    #[serde(rename = "invite_code")]
    pub invite_code: uuid::Uuid,
    #[serde(rename = "verifier")]
    pub verifier: uuid::Uuid,
}

impl InviteResponse {
    pub fn new(invite_code: uuid::Uuid, verifier: uuid::Uuid) -> InviteResponse {
        InviteResponse {
            invite_code,
            verifier,
        }
    }
}

