/*
 * rusty-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InviteBody {
    #[serde(rename = "author_signature")]
    pub author_signature: String,
    #[serde(rename = "exp")]
    pub exp: String,
    #[serde(rename = "invite_code")]
    pub invite_code: uuid::Uuid,
    #[serde(rename = "project_id")]
    pub project_id: uuid::Uuid,
}

impl InviteBody {
    pub fn new(author_signature: String, exp: String, invite_code: uuid::Uuid, project_id: uuid::Uuid) -> InviteBody {
        InviteBody {
            author_signature,
            exp,
            invite_code,
            project_id,
        }
    }
}

