/*
 * rusty-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewUserBody {
    #[serde(rename = "public_key")]
    pub public_key: String,
    #[serde(rename = "username")]
    pub username: String,
}

impl NewUserBody {
    pub fn new(public_key: String, username: String) -> NewUserBody {
        NewUserBody {
            public_key,
            username,
        }
    }
}

