/*
 * rusty-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectInfoV2 {
    #[serde(rename = "project_id")]
    pub project_id: String,
    #[serde(rename = "project_name")]
    pub project_name: String,
    #[serde(rename = "users")]
    pub users: Vec<models::User>,
}

impl ProjectInfoV2 {
    pub fn new(project_id: String, project_name: String, users: Vec<models::User>) -> ProjectInfoV2 {
        ProjectInfoV2 {
            project_id,
            project_name,
            users,
        }
    }
}

