/*
 * rusty-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemoveUserBody {
    #[serde(rename = "user_ids")]
    pub user_ids: Vec<String>,
}

impl RemoveUserBody {
    pub fn new(user_ids: Vec<String>) -> RemoveUserBody {
        RemoveUserBody {
            user_ids,
        }
    }
}

