/*
 * rusty-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetManyBody {
    #[serde(rename = "project_id")]
    pub project_id: uuid::Uuid,
    #[serde(rename = "variables")]
    pub variables: Vec<models::VariableInput>,
}

impl SetManyBody {
    pub fn new(project_id: uuid::Uuid, variables: Vec<models::VariableInput>) -> SetManyBody {
        SetManyBody {
            project_id,
            variables,
        }
    }
}

