/*
 * rusty-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StrippedUser {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "public_key")]
    pub public_key: String,
}

impl StrippedUser {
    pub fn new(id: String, public_key: String) -> StrippedUser {
        StrippedUser {
            id,
            public_key,
        }
    }
}

