/*
 * rusty-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateProjectV2 {
    #[serde(rename = "project_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub project_name: Option<Option<String>>,
}

impl UpdateProjectV2 {
    pub fn new() -> UpdateProjectV2 {
        UpdateProjectV2 {
            project_name: None,
        }
    }
}

