/*
 * rusty-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateManyBody {
    #[serde(rename = "variables")]
    pub variables: Vec<models::Variable>,
}

impl UpdateManyBody {
    pub fn new(variables: Vec<models::Variable>) -> UpdateManyBody {
        UpdateManyBody {
            variables,
        }
    }
}

