/*
 * rusty-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct User {
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "public_key")]
    pub public_key: String,
    #[serde(rename = "username")]
    pub username: String,
}

impl User {
    pub fn new(created_at: String, id: String, public_key: String, username: String) -> User {
        User {
            created_at,
            id,
            public_key,
            username,
        }
    }
}

