pub(super) use anyhow::{anyhow, Context, Result};
pub(super) use clap::Parser;
pub(super) use colored::Colorize;
pub(super) use std::result::Result::Ok as Good;

pub mod add_recipient;
pub mod behaviour;
pub mod config;
pub mod decrypt;
pub mod delete_key;
pub mod encrypt;
pub mod export;
pub mod gen;
pub mod get_config;
pub mod import;
pub mod init;
pub mod list_keys;
pub mod read_local;
pub mod run;
pub mod set;
pub mod set_local;
pub mod settings;
pub mod shell;
pub mod sign;
pub mod unset;
pub mod variables;
pub mod verify;
