use super::key::UnlockedKey;
use anyhow::{bail, Context, Ok, Result};
use rand::prelude::*;
use rand::rngs::OsRng;
use rayon::iter::{
    IndexedParallelIterator, IntoParallelRefIterator, ParallelIterator,
};
use smallvec::*;

use pgp::{
    composed::{
        ArmorOptions, Message, MessageBuilder, SignedPublicKey, SignedSecretKey,
    },
    crypto::{self, sym::SymmetricKeyAlgorithm},
};

#[derive(Debug)]
pub struct KeyPair {
    pub secret_key: SignedSecretKey,
    pub public_key: SignedPublicKey,
}

pub(crate) fn get_vault_location() -> anyhow::Result<std::path::PathBuf> {
    let path = crate::utils::paths::home_dir()
        .context("Failed to get home directory")?
        .join(".config")
        .join("envx")
        .join("keys");

    Ok(path)
}

pub fn user_id(nickname: &str) -> String {
    format!("{nickname} (generated by envx) <anon@envx.sh>")
}

pub fn generate_key_pair(nickname: &str, password: String) -> Result<KeyPair> {
    let mut key_params = pgp::composed::SecretKeyParamsBuilder::default();

    key_params
        // change to C25519 later
        // .key_type(composed::KeyType::ECDH(ECCCurve::Curve25519))
        .key_type(pgp::composed::KeyType::Rsa(4096))
        .can_certify(false)
        .can_sign(true)
        .can_encrypt(true)
        .passphrase(Some(password.clone()))
        .primary_user_id(user_id(nickname))
        .preferred_symmetric_algorithms(smallvec![
            crypto::sym::SymmetricKeyAlgorithm::AES256
        ]);

    let secret_key_params = key_params
        .build()
        .context("Failed to create secret key params.")?;

    let secret_key = secret_key_params
        .generate(OsRng)
        .context("Failed to generate a plain key.")?;

    let signed_secret_key = secret_key
        .sign(OsRng, &password.into())
        .context("Failed to sign secret key.")?;

    let signed_public_key = SignedPublicKey::from(signed_secret_key.clone());

    let key_pair = KeyPair {
        secret_key: signed_secret_key,
        public_key: signed_public_key,
    };

    Ok(key_pair)
}

pub fn encrypt<'a>(
    msg: &'a str,
    pubkeys: &'a [SignedPublicKey],
) -> Result<String> {
    if pubkeys.is_empty() {
        bail!("Cannot encrypt without a recipient public key");
    }
    let mut rng = StdRng::from_entropy();
    let mut builder = MessageBuilder::from_bytes("", msg.as_bytes().to_vec())
        .seipd_v1(&mut rng, SymmetricKeyAlgorithm::AES256);

    for (index, public_key) in pubkeys.iter().enumerate() {
        public_key.verify().with_context(|| {
            format!("Recipient public key {} is invalid", index + 1)
        })?;
        builder
            .encrypt_to_key(&mut rng, public_key)
            .with_context(|| {
                format!("Cannot encrypt for recipient public key {}", index + 1)
            })?;
    }

    let armor = builder.to_armored_string(&mut rng, ArmorOptions::default())?;
    Ok(armor)
}

pub fn decrypt(
    armored: &str,
    seckey: &SignedSecretKey,
    password: &str,
) -> Result<String> {
    let (msg, _) = Message::from_string(armored)
        .context("Failed to convert ascii armor message")?;

    if !matches!(&msg, Message::Encrypted { .. }) {
        bail!("Expected an encrypted OpenPGP message");
    }

    let mut decrypted = msg
        .decrypt(&password.into(), seckey)
        .context("Decrypting the message")?;

    if decrypted.is_compressed() {
        decrypted = decrypted
            .decompress()
            .context("Failed to decompress message")?;
    }

    Ok(decrypted.as_data_string()?)
}

pub fn decrypt_full_many(
    messages: Vec<String>,
    key: &UnlockedKey,
) -> Result<Vec<String>> {
    if messages.is_empty() {
        return Ok(vec![]);
    }

    let ssk = SignedSecretKey::try_from(key)?;
    decrypt_messages(&messages, &ssk, &key.password)
}

fn decrypt_messages(
    messages: &[String],
    secret: &SignedSecretKey,
    password: &str,
) -> Result<Vec<String>> {
    let decrypted = messages
        .par_iter()
        .enumerate()
        .map(|(index, message)| {
            decrypt(message, secret, password).with_context(|| {
                format!("Failed to decrypt variable {}", index + 1)
            })
        })
        .collect::<Result<Vec<String>>>()?;

    Ok(decrypted)
}

#[cfg(test)]
mod boundary_tests {
    use super::*;
    use pgp::composed::{KeyType, SecretKeyParamsBuilder};

    fn generate(kind: KeyType) -> SignedSecretKey {
        SecretKeyParamsBuilder::default()
            .key_type(kind)
            .can_sign(true)
            .primary_user_id("boundary-test".into())
            .build()
            .unwrap()
            .generate(OsRng)
            .unwrap()
            .sign(OsRng, &"".into())
            .unwrap()
    }
    #[test]
    fn crypto_boundaries_fail_closed_without_panicking() {
        let secret = generate(KeyType::Rsa(2048));
        let public = SignedPublicKey::from(secret.clone());
        let encrypted = encrypt("valid secret", &[public]).unwrap();
        assert_eq!(decrypt(&encrypted, &secret, "").unwrap(), "valid secret");
        let plain = MessageBuilder::from_bytes("", b"not encrypted".to_vec())
            .to_armored_string(OsRng, ArmorOptions::default())
            .unwrap();
        assert!(decrypt(&plain, &secret, "")
            .unwrap_err()
            .to_string()
            .contains("Expected an encrypted"));
        assert!(decrypt("malformed armor", &secret, "").is_err());
        assert!(decrypt_messages(&[encrypted, plain], &secret, "").is_err());
        assert!(encrypt("secret", &[]).is_err());
        let signing_only = SignedPublicKey::from(generate(KeyType::Ed25519));
        assert!(encrypt("secret", &[signing_only]).is_err());
    }
}
