use super::key::UnlockedKey;
use anyhow::{bail, Context, Ok, Result};
use hex::ToHex;
use rand::prelude::*;
use rand::rngs::OsRng;
use rayon::iter::{IntoParallelRefIterator, ParallelIterator};
use smallvec::*;

use pgp::{
    composed::{
        ArmorOptions, Message, MessageBuilder, SignedPublicKey, SignedSecretKey,
    },
    crypto::{self, sym::SymmetricKeyAlgorithm},
};

#[derive(Debug)]
pub struct KeyPair {
    pub secret_key: SignedSecretKey,
    pub public_key: SignedPublicKey,
}

pub(crate) fn get_vault_location() -> anyhow::Result<std::path::PathBuf> {
    let path = home::home_dir()
        .context("Failed to get home directory")?
        .join(".config")
        .join("envx")
        .join("keys");

    Ok(path)
}

pub fn user_id(nickname: &str) -> String {
    format!("{nickname} (generated by envx) <anon@envx.sh>")
}

pub fn generate_key_pair(nickname: &str, password: String) -> Result<KeyPair> {
    let mut key_params = pgp::composed::SecretKeyParamsBuilder::default();

    key_params
        // change to C25519 later
        // .key_type(composed::KeyType::ECDH(ECCCurve::Curve25519))
        .key_type(pgp::composed::KeyType::Rsa(4096))
        .can_certify(false)
        .can_sign(true)
        .can_encrypt(true)
        .passphrase(Some(password.clone()))
        .primary_user_id(user_id(nickname))
        .preferred_symmetric_algorithms(smallvec![
            crypto::sym::SymmetricKeyAlgorithm::AES256
        ]);

    let secret_key_params = key_params
        .build()
        .context("Failed to create secret key params.")?;

    let secret_key = secret_key_params
        .generate(OsRng)
        .context("Failed to generate a plain key.")?;

    let signed_secret_key = secret_key
        .sign(OsRng, &password.into())
        .context("Failed to sign secret key.")?;

    let signed_public_key = SignedPublicKey::from(signed_secret_key.clone());

    let key_pair = KeyPair {
        secret_key: signed_secret_key,
        public_key: signed_public_key,
    };

    Ok(key_pair)
}

pub fn encrypt<'a>(
    msg: &'a str,
    pubkeys: &'a [SignedPublicKey],
) -> Result<String> {
    let mut rng = StdRng::from_entropy();
    let mut builder = MessageBuilder::from_bytes("", msg.as_bytes().to_vec())
        .seipd_v1(&mut rng, SymmetricKeyAlgorithm::AES256);

    pubkeys.iter().for_each(|pk| {
        builder.encrypt_to_key(&mut rng, pk).unwrap();
    });

    let armor = builder.to_armored_string(&mut rng, ArmorOptions::default())?;
    Ok(armor)
}

trait GetRecipients {
    fn get_recipients(&self) -> Vec<&pgp::types::KeyId>;
}

impl GetRecipients for pgp::composed::Message<'_> {
    fn get_recipients(&self) -> Vec<&pgp::types::KeyId> {
        match self {
            Message::Encrypted { esk, .. } => esk
                .iter()
                .filter_map(|e| match e {
                    pgp::composed::Esk::PublicKeyEncryptedSessionKey(k) => {
                        k.id().ok()
                    }
                    _ => None,
                })
                .collect::<Vec<&pgp::types::KeyId>>(),
            _ => todo!(),
        }
    }
}

pub fn decrypt(
    armored: &str,
    seckey: &SignedSecretKey,
    password: &str,
) -> Result<String> {
    let (msg, _) = Message::from_string(armored)
        .context("Failed to convert ascii armor message")?;

    let mut decrypted = msg
        .decrypt(&password.into(), seckey)
        .context("Decrypting the message")?;

    if decrypted.is_compressed() {
        decrypted = decrypted
            .decompress()
            .context("Failed to decompress message")?;
    }

    Ok(decrypted.as_data_string()?)
}

pub fn decrypt_full_many(
    messages: Vec<String>,
    key: &UnlockedKey,
) -> Result<Vec<String>> {
    let first = if let Some(first) = messages.first() {
        first
    } else {
        return Ok(vec![]);
    };

    let (msg, _) = Message::from_string(first.as_str())?;

    let recipients: Vec<String> = msg
        .get_recipients()
        .iter()
        .map(|e| e.encode_hex_upper())
        .collect();

    let last_16 = key
        .key
        .fingerprint
        .chars()
        .rev()
        .take(16)
        .collect::<Vec<_>>()
        .into_iter()
        .rev()
        .collect::<String>()
        .to_uppercase();
    if !recipients.contains(&last_16) {
        bail!("This message was not encrypted for your key.");
    }

    let ssk = SignedSecretKey::try_from(key)?;
    let decrypted = messages
        .par_iter()
        .map(|m| decrypt(m, &ssk, &key.password))
        .collect::<Result<Vec<String>>>()?;

    Ok(decrypted)
}
